import { Lato } from "next/font/google";
import ThemeRegistry from "@/theme/themeProvider";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato',
})

export const metadata = {
  title: "Quick App",
  description: "Generated by Quick app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${lato.variable} antialiased`}>
        <ThemeRegistry>
          {children}
          <ToastContainer 
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            pauseOnHover
            draggable
            theme="light"
          />
        </ThemeRegistry>
      </body>
    </html>
  );
}
